### ISSUE TITLE
getPackFormat("1.20.2") incorrectly returns 17

### ISSUE THREAD

**Issue by lafkpages** [Nixinova/pack-format#1]
The pack format for 1.20.2 should be 18, but this library says it's 17.
https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack#%22pack_format%22

**Comment by Nixinova** [comment]
That's right, i havent updated this since 1.20.2 released. I'll make a new release now for it.

**Comment by Nixinova** [comment]
Fixed in 1.3.10
